### ISSUE TITLE
Content-Type header added in GET methods

### ISSUE THREAD

**Issue by clubandres** [amzn/amazon-pay-api-sdk-nodejs#13]
The api
https://pay-api.amazon.com/v2/authorizationTokens/{mwsAuthToken}?merchantId={merchantId} uses HTTP GET

The header content-type its being added to the signature, in most cases there is no header present and depending on the rest client and proxies some remove automatically that header

Is it possible to remove this header from the signature of AMZN-PAY-RSASSA-PSS?

**Comment by shangamesh** [comment]
We are checking with our internal team about this case. We will keep you updated about this case

**Comment by shangamesh** [comment]
In SDK, the headers like x-amz-pay-region, x-amz-pay-host, x-amz-pay-date, accept, user-agent are added along with content-type while creating signature & gets appended before calling API. Are you facing issue that only content-type is getting excluded ?

**Comment by clubandres** [comment]
The issue comes because adding that header, (Content-Type) as when the HTTP GET is used, this header is removed from Proxies when performing the API Call to Amazon.  That generates the problem,  does make sense adding this header into the signature when is an HTTP Get?  In our case its already fixed, we choose to make a custom implementation and avoid using the SDK for now.

**Comment by shangamesh** [comment]
Hi 
I checked with internal team & found that we support only content-type as application/json in our system & we can’t remove those headers for security reasons. Generally proxies/gateways should not remove the HTTP header while making an API call which need to be checked with proxy which you are using

**Comment by clubandres** [comment]
Hi thanks for your attention, this has already been addressed in our side. We could not change the proxy behaviour but it is solved. Closing this issue as we do not need more the sdk.  


best regards
